- type: job
  id: NCCitizen
  name: job-name-nc-citizen
  description: job-description-nc-citizen
  playTimeTracker: JobNCCitizen
  startingGear: NCCitizenGear
  icon: JobIconNCCitizen
  supervisors: job-supervisors-nobody
  setPreference: false
  overrideConsoleVisibility: false

- type: startingGear
  id: NCCitizenGear
  equipment:
    id: NCCitizenPDA
    ears: ClothingHeadsetGrey

- type: playTimeTracker
  id: JobNCCitizen

- type: jobIcon
  parent: JobIcon
  id: JobIconNCCitizen
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: Passenger
  jobName: job-name-nc-citizen

- type: entity
  parent: PassengerIDCard
  id: NCCitizenIDCard

- type: entity
  parent: PassengerPDA
  id: NCCitizenPDA
  components:
  - type: Pda
    id: NCCitizenIDCard
