# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: department
  id: NCPD
  name: department-name-ncpd
  description: department-desc-ncpd
  color: "#4777C8"
  weight: 50
  ncSelectable: true
  ncEntryJob: NCPDCadet
  ncPersonnelManagers: [ NCPDChief, NCPDCommander, NCPDLieutenant ]
  ncPositionLimits:
    NCPDChief: 1
    NCPDCommander: 2
    NCPDLieutenant: 4
    NCPDInspector: 6
    NCPDSergeant: 8
    NCPDOfficer: 20
    NCPDCadet: 20
  ncPositionRanks:
    NCPDChief: 100
    NCPDCommander: 90
    NCPDLieutenant: 80
    NCPDInspector: 70
    NCPDSergeant: 60
    NCPDOfficer: 50
    NCPDCadet: 10
  roles: [ NCPDChief, NCPDCommander, NCPDLieutenant, NCPDInspector, NCPDSergeant, NCPDOfficer, NCPDCadet ]

- type: department
  id: TraumaTeam
  name: department-name-trauma-team
  description: department-desc-trauma-team
  color: "#4FB9D7"
  weight: 40
  ncSelectable: true
  ncEntryJob: TraumaTeamParamedic
  roles: [ TraumaTeamParamedic, TraumaTeamOperative ]

- type: department
  id: MedicalNC
  name: department-name-medical-nc
  description: department-desc-medical-nc
  color: "#66C58D"
  weight: 35
  ncSelectable: true
  ncEntryJob: TraumaTeamIntern
  roles: [ TraumaTeamChief, TraumaTeamDoctor, TraumaTeamCoroner, TraumaTeamPsych, TraumaTeamIntern, TraumaTeamTech ]

- type: department
  id: Biotechnica
  name: department-name-biotechnica
  description: department-desc-biotechnica
  color: "#6DB15C"
  weight: 30
  ncSelectable: true
  ncEntryJob: BiotechnicaOperative
  roles: [ BiotechnicaChief, BiotechnicaOperativeLead, BiotechnicaOperative, BiotechnicaRigger, BiotechnicaBotanist, BiotechnicaMedTech, BiotechnicaTech, BiotechnicaNetrunner, BiotechnicaParamedic ]

- type: department
  id: Militech
  name: department-name-militech
  description: department-desc-militech
  color: "#8A8C91"
  weight: 30
  ncSelectable: true
  ncEntryJob: MilitechOperative
  roles: [ MilitechChief, MilitechOperativeLead, MilitechOperative, MilitechRigger, MilitechNetrunner, MilitechSecuritySpecialist, MilitechCombatMedic, MilitechTech, MilitechQuartermaster ]

- type: department
  id: Zhirafa
  name: department-name-zhirafa
  description: department-desc-zhirafa
  color: "#D8A650"
  weight: 10
  ncSelectable: true
  ncEntryJob: ZhirafaJanitor
  roles: [ ZhirafaJanitor, ZhirafaEngineer ]
