// SPDX-FileCopyrightText: 2026 Astro
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Bank.ATM;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Bank.ATM;

[GenerateTypedNameReferences]
public sealed partial class NCAtmWindow : FancyWindow
{
    public event Action<int>? OnWithdraw;
    public event Action? OnDeposit;
    public event Action<string, string>? OnLogin;
    public event Action? OnLogout;

    public NCAtmWindow()
    {
        RobustXamlLoader.Load(this);

        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(WithdrawEdit.Text, out var amount))
                OnWithdraw?.Invoke(amount);
        };
        DepositButton.OnPressed += _ => OnDeposit?.Invoke();
        LoginButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(AccountNumberEdit.Text) &&
                !string.IsNullOrWhiteSpace(PinEdit.Text))
            {
                OnLogin?.Invoke(AccountNumberEdit.Text.Trim(), PinEdit.Text.Trim());
            }
        };
        LogoutButton.OnPressed += _ => OnLogout?.Invoke();
    }

    public void UpdateState(NCAtmBoundUserInterfaceState state)
    {
        LoginContainer.Visible = !state.IsLoggedIn;
        AccountContainer.Visible = state.IsLoggedIn;
        StatusLabel.Text = Loc.GetString(state.IsLoggedIn
            ? "nc-atm-status-account"
            : "nc-atm-status-unauthorized", ("account", state.AccountNumber));
        StatusLabel.FontColorOverride = state.IsLoggedIn ? Color.Green : Color.Red;
        BalanceLabel.Text = Loc.GetString("nc-atm-credits", ("amount", state.BankBalance));
        TaxLabel.Text = $"{state.TaxRate * 100:0}%";
        DepositLabel.Text = Loc.GetString("nc-atm-credits", ("amount", state.DepositAmount));
        WithdrawButton.Disabled = !state.IsLoggedIn;
        WithdrawEdit.Editable = state.IsLoggedIn;
        DepositButton.Disabled = !state.IsLoggedIn || state.DepositAmount <= 0;

        if (state.IsLoggedIn)
        {
            AccountNumberEdit.Text = string.Empty;
            PinEdit.Text = string.Empty;
        }
        else if (string.IsNullOrEmpty(AccountNumberEdit.Text))
        {
            AccountNumberEdit.Text = state.OwnAccountNumber;
        }
    }
}
