// SPDX-FileCopyrightText: 2026 Astro
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Bank.Budget;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Bank.Budget;

[GenerateTypedNameReferences]
public sealed partial class NCOrganizationBudgetConsoleWindow : FancyWindow
{
    public event Action<string>? OnDeposit;
    public event Action<int, string>? OnWithdraw;

    public NCOrganizationBudgetConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        DepositButton.OnPressed += _ => OnDeposit?.Invoke(ReasonEdit.Text.Trim());
        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(WithdrawAmountEdit.Text, out var amount))
                OnWithdraw?.Invoke(amount, ReasonEdit.Text.Trim());
        };
    }

    public void UpdateState(NCOrganizationBudgetConsoleState state)
    {
        OrganizationLabel.Text = state.OrganizationName;
        BalanceLabel.Text = Loc.GetString("nc-budget-credits", ("amount", state.Balance));
        InsertedCashLabel.Text = Loc.GetString("nc-budget-credits", ("amount", state.InsertedCash));
        ReadOnlyLabel.Visible = !state.CanManage;
        ReasonEdit.Editable = state.CanManage;
        WithdrawAmountEdit.Editable = state.CanManage;
        DepositButton.Disabled = !state.CanManage || state.InsertedCash <= 0;
        WithdrawButton.Disabled = !state.CanManage;

        HistoryList.Clear();
        foreach (var transaction in state.Transactions)
        {
            var action = Loc.GetString($"nc-budget-action-{transaction.Type.ToLowerInvariant()}");
            HistoryList.AddItem(Loc.GetString("nc-budget-history-line",
                ("time", transaction.CreatedAt.ToLocalTime().ToString("g")),
                ("actor", transaction.ActorName),
                ("action", action),
                ("amount", transaction.Amount),
                ("balance", transaction.BalanceAfter),
                ("reason", transaction.Reason)));
        }

        NoHistoryLabel.Visible = state.Transactions.Count == 0;
    }
}
