// SPDX-FileCopyrightText: 2026 Astro
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Police.UI;
using Content.Shared.Database._NC.Police;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._NC.Police;

[GenerateTypedNameReferences]
public sealed partial class NCPoliceRecordsWindow : FancyWindow
{
    private readonly IPrototypeManager _prototypes;
    private readonly Dictionary<long, NCPoliceWarrantSummary> _warrants = new();
    private readonly Dictionary<long, NCPoliceFineSummary> _fines = new();
    private int? _selectedCharacterId;
    private long? _selectedCaseId;
    private long? _selectedWarrantId;
    private long? _selectedFineId;

    public event Action<string>? OnSearch;
    public event Action<int>? OnSelected;
    public event Action<int, NCPoliceOperationalStatus, string>? OnStatusChanged;
    public event Action<string, string>? OnCreateCase;
    public event Action<long>? OnSelectCase;
    public event Action<long, NCPoliceCaseSubjectRole>? OnAddCaseSubject;
    public event Action<long, string>? OnAddCaseEntry;
    public event Action<long, NCPoliceCaseStatus, string>? OnCaseStatusChanged;
    public event Action<NCPoliceWarrantType, string, long?>? OnCreateWarrant;
    public event Action<long, NCPoliceWarrantStatus, string>? OnResolveWarrant;
    public event Action<string, string, int>? OnCreateFine;
    public event Action<long, NCPoliceFineStatus, string>? OnFineStatusChanged;

    public NCPoliceRecordsWindow(IPrototypeManager prototypes)
    {
        RobustXamlLoader.Load(this);
        _prototypes = prototypes;

        RecordTabs.SetTabTitle(0, Loc.GetString("nc-police-tab-dossier"));
        RecordTabs.SetTabTitle(1, Loc.GetString("nc-police-tab-cases"));
        RecordTabs.SetTabTitle(2, Loc.GetString("nc-police-tab-warrants"));
        RecordTabs.SetTabTitle(3, Loc.GetString("nc-police-tab-fines"));

        foreach (var status in Enum.GetValues<NCPoliceOperationalStatus>())
            StatusSelector.AddItem(StatusName(status), (int) status);
        foreach (var role in Enum.GetValues<NCPoliceCaseSubjectRole>())
            CaseSubjectRoleSelector.AddItem(CaseSubjectRoleName(role), (int) role);
        foreach (var status in Enum.GetValues<NCPoliceCaseStatus>())
            CaseStatusSelector.AddItem(CaseStatusName(status), (int) status);
        foreach (var type in Enum.GetValues<NCPoliceWarrantType>())
            NewWarrantTypeSelector.AddItem(WarrantTypeName(type), (int) type);
        foreach (var status in Enum.GetValues<NCPoliceWarrantStatus>().Where(value => value != NCPoliceWarrantStatus.Active))
            WarrantResolutionStatusSelector.AddItem(WarrantStatusName(status), (int) status);
        foreach (var status in Enum.GetValues<NCPoliceFineStatus>()
                     .Where(value => value is NCPoliceFineStatus.Contested or NCPoliceFineStatus.Voided or NCPoliceFineStatus.Overdue))
            FineStatusSelector.AddItem(FineStatusName(status), (int) status);

        WireOptionButton(StatusSelector);
        WireOptionButton(CaseSubjectRoleSelector);
        WireOptionButton(CaseStatusSelector);
        WireOptionButton(NewWarrantTypeSelector);
        WireOptionButton(WarrantResolutionStatusSelector);
        WireOptionButton(FineStatusSelector);

        SearchButton.OnPressed += _ => SubmitSearch();
        SearchEdit.OnTextEntered += _ => SubmitSearch();
        ResultsList.OnItemSelected += args =>
        {
            if (ResultsList[args.ItemIndex].Metadata is int characterId)
                OnSelected?.Invoke(characterId);
        };
        ApplyButton.OnPressed += _ =>
        {
            var reason = ReasonEdit.Text.Trim();
            if (_selectedCharacterId is { } characterId && reason.Length > 0)
                OnStatusChanged?.Invoke(characterId, (NCPoliceOperationalStatus) StatusSelector.SelectedId, reason);
        };

        CreateCaseButton.OnPressed += _ =>
        {
            var title = NewCaseTitle.Text.Trim();
            var summary = Rope.Collapse(NewCaseSummary.TextRope).Trim();
            if (_selectedCharacterId != null && title.Length > 0 && summary.Length > 0)
                OnCreateCase?.Invoke(title, summary);
        };
        CaseList.OnItemSelected += args =>
        {
            if (CaseList[args.ItemIndex].Metadata is long caseId)
                OnSelectCase?.Invoke(caseId);
        };
        LinkSubjectButton.OnPressed += _ =>
        {
            if (_selectedCaseId is { } caseId && _selectedCharacterId != null)
                OnAddCaseSubject?.Invoke(caseId, (NCPoliceCaseSubjectRole) CaseSubjectRoleSelector.SelectedId);
        };
        AddCaseReportButton.OnPressed += _ =>
        {
            var text = Rope.Collapse(CaseReportEdit.TextRope).Trim();
            if (_selectedCaseId is { } caseId && text.Length > 0)
                OnAddCaseEntry?.Invoke(caseId, text);
        };
        ApplyCaseStatusButton.OnPressed += _ =>
        {
            var reason = CaseStatusReasonEdit.Text.Trim();
            if (_selectedCaseId is { } caseId && reason.Length > 0)
                OnCaseStatusChanged?.Invoke(caseId, (NCPoliceCaseStatus) CaseStatusSelector.SelectedId, reason);
        };

        WarrantList.OnItemSelected += args =>
        {
            if (WarrantList[args.ItemIndex].Metadata is long warrantId && _warrants.TryGetValue(warrantId, out var warrant))
            {
                _selectedWarrantId = warrantId;
                UpdateWarrantDetail(warrant);
            }
        };
        CreateWarrantButton.OnPressed += _ =>
        {
            var reason = Rope.Collapse(NewWarrantReason.TextRope).Trim();
            if (_selectedCharacterId != null && reason.Length > 0)
            {
                var caseId = LinkWarrantToCase.Pressed ? _selectedCaseId : null;
                OnCreateWarrant?.Invoke((NCPoliceWarrantType) NewWarrantTypeSelector.SelectedId, reason, caseId);
            }
        };
        ResolveWarrantButton.OnPressed += _ =>
        {
            var reason = Rope.Collapse(WarrantResolutionReason.TextRope).Trim();
            if (_selectedWarrantId is { } warrantId && reason.Length > 0)
            {
                OnResolveWarrant?.Invoke(
                    warrantId,
                    (NCPoliceWarrantStatus) WarrantResolutionStatusSelector.SelectedId,
                    reason);
            }
        };
        FineList.OnItemSelected += args =>
        {
            if (FineList[args.ItemIndex].Metadata is long fineId && _fines.TryGetValue(fineId, out var fine))
            {
                _selectedFineId = fineId;
                UpdateFineDetail(fine);
            }
        };
        CreateFineButton.OnPressed += _ =>
        {
            var article = NewFineArticle.Text.Trim();
            var reason = Rope.Collapse(NewFineReason.TextRope).Trim();
            if (_selectedCharacterId != null && article.Length > 0 && reason.Length > 0 &&
                int.TryParse(NewFineAmount.Text, out var amount) && amount > 0)
                OnCreateFine?.Invoke(article, reason, amount);
        };
        ApplyFineStatusButton.OnPressed += _ =>
        {
            var reason = Rope.Collapse(FineStatusReason.TextRope).Trim();
            if (_selectedFineId is { } fineId && reason.Length > 0)
                OnFineStatusChanged?.Invoke(fineId, (NCPoliceFineStatus) FineStatusSelector.SelectedId, reason);
        };
    }

    public void UpdateData(NCPoliceRecordsUpdateMessage update)
    {
        UpdateResidentList(update.SearchResults);
        UpdateDossier(update);
        UpdateCases(update);
        UpdateWarrants(update.Warrants);
        UpdateFines(update.Fines);
    }

    private void UpdateResidentList(List<NCPoliceRecordSummary> results)
    {
        ResultsList.Clear();
        AddResultGroup(Loc.GetString("nc-police-records-present-group"), results.Where(value => value.PresentThisRound));
        AddResultGroup(Loc.GetString("nc-police-records-registry-group"), results.Where(value => !value.PresentThisRound));
        NoResultsLabel.Visible = results.Count == 0;
    }

    private void UpdateDossier(NCPoliceRecordsUpdateMessage update)
    {
        var selected = update.SelectedRecord;
        RecordContainer.Visible = selected != null;
        SelectPrompt.Visible = selected == null;
        if (selected == null)
        {
            _selectedCharacterId = null;
            return;
        }

        _selectedCharacterId = selected.CharacterId;
        CharacterNameLabel.Text = selected.CharacterName;
        JobLabel.Text = GetJobName(selected.JobPrototypeId);
        CurrentStatusLabel.Text = StatusName(selected.Status);
        CurrentReasonLabel.Text = selected.Reason ?? Loc.GetString("generic-not-available-shorthand");
        UpdatedByLabel.Text = string.IsNullOrEmpty(selected.UpdatedByName)
            ? Loc.GetString("generic-not-available-shorthand")
            : selected.UpdatedByName;
        StatusSelector.SelectId((int) selected.Status);
        ApplyButton.Disabled = !update.CanEdit;
        ReasonEdit.Editable = update.CanEdit;

        HistoryList.Clear();
        foreach (var entry in update.History)
        {
            var reason = entry.Reason ?? Loc.GetString("generic-not-available-shorthand");
            HistoryList.AddItem(Loc.GetString(
                "nc-police-records-history-line",
                ("time", entry.CreatedAt.ToLocalTime().ToString("g")),
                ("actor", entry.ActorName),
                ("oldStatus", StatusName(entry.PreviousStatus)),
                ("newStatus", StatusName(entry.NewStatus)),
                ("reason", reason)));
        }
        NoHistoryLabel.Visible = update.History.Count == 0;
    }

    private void UpdateCases(NCPoliceRecordsUpdateMessage update)
    {
        CaseList.Clear();
        foreach (var policeCase in update.Cases)
        {
            CaseList.AddItem(
                $"#{policeCase.CaseId} {policeCase.Title} — {CaseStatusName(policeCase.Status)}",
                metadata: policeCase.CaseId);
        }

        var selected = update.SelectedCase;
        _selectedCaseId = selected?.CaseId;
        CaseSelectPrompt.Visible = selected == null;
        CaseDetailContainer.Visible = selected != null;
        WarrantCaseLinkLabel.Text = selected == null
            ? Loc.GetString("nc-police-warrant-no-case-link")
            : Loc.GetString("nc-police-warrant-case-link", ("caseId", selected.CaseId));
        LinkWarrantToCase.Disabled = selected == null;
        if (selected == null)
            return;

        CaseTitleLabel.Text = $"#{selected.CaseId} {selected.Title}";
        CaseStatusLabel.Text = Loc.GetString("nc-police-case-status-line", ("status", CaseStatusName(selected.Status)));
        CaseSummaryLabel.Text = selected.Summary;
        CaseStatusSelector.SelectId((int) selected.Status);

        CaseSubjectsList.Clear();
        foreach (var subject in selected.Subjects)
        {
            CaseSubjectsList.AddItem(Loc.GetString(
                "nc-police-case-subject-line",
                ("name", subject.CharacterName),
                ("role", CaseSubjectRoleName(subject.Role))));
        }

        CaseEntriesList.Clear();
        foreach (var entry in selected.Entries)
        {
            var text = FormatCaseEntry(entry);
            CaseEntriesList.AddItem(Loc.GetString(
                "nc-police-case-entry-line",
                ("time", entry.CreatedAt.ToLocalTime().ToString("g")),
                ("author", entry.AuthorName),
                ("text", text)));
        }
    }

    private void UpdateWarrants(List<NCPoliceWarrantSummary> warrants)
    {
        _warrants.Clear();
        WarrantList.Clear();
        foreach (var warrant in warrants)
        {
            _warrants[warrant.WarrantId] = warrant;
            WarrantList.AddItem(
                $"#{warrant.WarrantId} {warrant.TargetName} — {WarrantTypeName(warrant.Type)} / {WarrantStatusName(warrant.Status)}",
                metadata: warrant.WarrantId);
        }

        if (_selectedWarrantId is { } selectedId && _warrants.TryGetValue(selectedId, out var selected))
            UpdateWarrantDetail(selected);
        else
        {
            _selectedWarrantId = null;
            WarrantDetailContainer.Visible = false;
        }
    }

    private void UpdateFines(List<NCPoliceFineSummary> fines)
    {
        _fines.Clear();
        FineList.Clear();
        foreach (var fine in fines)
        {
            _fines[fine.FineId] = fine;
            FineList.AddItem(Loc.GetString("nc-police-fine-list-line", ("id", fine.FineId),
                ("name", fine.TargetName), ("amount", fine.Amount), ("status", FineStatusName(fine.Status))),
                metadata: fine.FineId);
        }
        if (_selectedFineId is { } selectedId && _fines.TryGetValue(selectedId, out var selected))
            UpdateFineDetail(selected);
        else
        {
            _selectedFineId = null;
            FineDetailContainer.Visible = false;
        }
    }

    private void UpdateFineDetail(NCPoliceFineSummary fine)
    {
        FineDetailContainer.Visible = true;
        FineTitleLabel.Text = Loc.GetString("nc-police-fine-title-line", ("id", fine.FineId),
            ("article", fine.Article), ("name", fine.TargetName), ("amount", fine.Amount));
        FineStatusLabel.Text = Loc.GetString("nc-police-fine-status-line", ("status", FineStatusName(fine.Status)));
        FineReasonLabel.Text = Loc.GetString("nc-police-fine-reason-line", ("reason", fine.Reason));
        FineIssuedLabel.Text = Loc.GetString("nc-police-fine-issued-line", ("actor", fine.IssuedByName),
            ("time", fine.IssuedAt.ToLocalTime().ToString("g")));
        FineDueLabel.Text = Loc.GetString("nc-police-fine-due-line", ("time", fine.DueAt.ToLocalTime().ToString("g")));
        var editable = fine.Status is not (NCPoliceFineStatus.Paid or NCPoliceFineStatus.Voided);
        FineStatusSelector.Disabled = !editable;
        FineStatusReason.Editable = editable;
        ApplyFineStatusButton.Disabled = !editable;
    }

    private static string FormatCaseEntry(NCPoliceCaseEntrySummary entry)
    {
        return entry.EntryType switch
        {
            NCPoliceCaseEntryType.StatusChanged when entry.PreviousStatus is { } previous && entry.NewStatus is { } next =>
                Loc.GetString(
                    "nc-police-case-entry-status-changed",
                    ("oldStatus", CaseStatusName(previous)),
                    ("newStatus", CaseStatusName(next)),
                    ("reason", entry.Text)),
            NCPoliceCaseEntryType.SubjectAdded when entry.SubjectRole is { } role =>
                Loc.GetString(
                    "nc-police-case-entry-subject-added",
                    ("name", entry.SubjectName ?? Loc.GetString("generic-not-available-shorthand")),
                    ("role", CaseSubjectRoleName(role))),
            _ => entry.Text,
        };
    }

    private void UpdateWarrantDetail(NCPoliceWarrantSummary warrant)
    {
        WarrantDetailContainer.Visible = true;
        WarrantTitleLabel.Text = $"#{warrant.WarrantId} {WarrantTypeName(warrant.Type)} — {warrant.TargetName}";
        WarrantStatusLabel.Text = Loc.GetString("nc-police-warrant-status-line", ("status", WarrantStatusName(warrant.Status)));
        WarrantReasonLabel.Text = Loc.GetString("nc-police-warrant-reason-line", ("reason", warrant.Reason));
        WarrantIssuedByLabel.Text = Loc.GetString(
            "nc-police-warrant-issued-line",
            ("actor", warrant.IssuedByName),
            ("time", warrant.IssuedAt.ToLocalTime().ToString("g")));
        WarrantResolutionLabel.Text = warrant.ResolvedAt == null
            ? Loc.GetString("nc-police-warrant-not-resolved")
            : Loc.GetString(
                "nc-police-warrant-resolution-line",
                ("actor", warrant.ResolvedByName ?? string.Empty),
                ("reason", warrant.ResolutionReason ?? string.Empty));
        ResolveWarrantButton.Disabled = warrant.Status != NCPoliceWarrantStatus.Active;
        WarrantResolutionStatusSelector.Disabled = warrant.Status != NCPoliceWarrantStatus.Active;
        WarrantResolutionReason.Editable = warrant.Status == NCPoliceWarrantStatus.Active;
    }

    private void SubmitSearch()
    {
        OnSearch?.Invoke(SearchEdit.Text.Trim());
    }

    private void AddResultGroup(string heading, IEnumerable<NCPoliceRecordSummary> results)
    {
        var entries = results.ToList();
        if (entries.Count == 0)
            return;

        ResultsList.AddItem(heading, selectable: false);
        foreach (var result in entries)
            ResultsList.AddItem($"{result.CharacterName} — {StatusName(result.Status)}", metadata: result.CharacterId);
    }

    private string GetJobName(string? jobPrototypeId)
    {
        if (jobPrototypeId != null && _prototypes.TryIndex<JobPrototype>(jobPrototypeId, out var job))
            return job.LocalizedName;
        return Loc.GetString("job-name-passenger");
    }

    private static void WireOptionButton(OptionButton button)
    {
        button.OnItemSelected += args => args.Button.SelectId(args.Id);
    }

    private static string StatusName(NCPoliceOperationalStatus status) =>
        Loc.GetString($"nc-police-status-{status.ToString().ToLowerInvariant()}");
    private static string CaseStatusName(NCPoliceCaseStatus status) =>
        Loc.GetString($"nc-police-case-status-{status.ToString().ToLowerInvariant()}");
    private static string CaseSubjectRoleName(NCPoliceCaseSubjectRole role) =>
        Loc.GetString($"nc-police-case-role-{role.ToString().ToLowerInvariant()}");
    private static string WarrantTypeName(NCPoliceWarrantType type) =>
        Loc.GetString($"nc-police-warrant-type-{type.ToString().ToLowerInvariant()}");
    private static string WarrantStatusName(NCPoliceWarrantStatus status) =>
        Loc.GetString($"nc-police-warrant-status-{status.ToString().ToLowerInvariant()}");
    private static string FineStatusName(NCPoliceFineStatus status) =>
        Loc.GetString($"nc-police-fine-status-{status.ToString().ToLowerInvariant()}");
}
