// SPDX-FileCopyrightText: 2026 Astro
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Police.UI;
using Content.Shared.Database._NC.Police;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._NC.Police;

[GenerateTypedNameReferences]
public sealed partial class NCPoliceRecordsWindow : FancyWindow
{
    private readonly IPrototypeManager _prototypes;
    private int? _selectedCharacterId;

    public event Action<string>? OnSearch;
    public event Action<int>? OnSelected;
    public event Action<int, NCPoliceOperationalStatus, string>? OnStatusChanged;

    public NCPoliceRecordsWindow(IPrototypeManager prototypes)
    {
        RobustXamlLoader.Load(this);
        _prototypes = prototypes;

        foreach (var status in Enum.GetValues<NCPoliceOperationalStatus>())
            StatusSelector.AddItem(StatusName(status), (int) status);

        SearchButton.OnPressed += _ => SubmitSearch();
        SearchEdit.OnTextEntered += _ => SubmitSearch();
        ResultsList.OnItemSelected += args =>
        {
            if (ResultsList[args.ItemIndex].Metadata is int characterId)
                OnSelected?.Invoke(characterId);
        };
        StatusSelector.OnItemSelected += args => args.Button.SelectId(args.Id);
        ApplyButton.OnPressed += _ =>
        {
            var reason = ReasonEdit.Text.Trim();
            if (_selectedCharacterId is { } characterId && reason.Length > 0)
            {
                OnStatusChanged?.Invoke(
                    characterId,
                    (NCPoliceOperationalStatus) StatusSelector.SelectedId,
                    reason);
            }
        };
    }

    public void UpdateData(NCPoliceRecordsUpdateMessage update)
    {
        ResultsList.Clear();
        AddResultGroup(
            Loc.GetString("nc-police-records-present-group"),
            update.SearchResults.Where(result => result.PresentThisRound));
        AddResultGroup(
            Loc.GetString("nc-police-records-registry-group"),
            update.SearchResults.Where(result => !result.PresentThisRound));

        NoResultsLabel.Visible = update.SearchResults.Count == 0;
        var selected = update.SelectedRecord;
        RecordContainer.Visible = selected != null;
        SelectPrompt.Visible = selected == null;
        if (selected == null)
        {
            _selectedCharacterId = null;
            return;
        }

        _selectedCharacterId = selected.CharacterId;
        CharacterNameLabel.Text = selected.CharacterName;
        JobLabel.Text = GetJobName(selected.JobPrototypeId);
        CurrentStatusLabel.Text = StatusName(selected.Status);
        CurrentReasonLabel.Text = selected.Reason ?? Loc.GetString("generic-not-available-shorthand");
        UpdatedByLabel.Text = string.IsNullOrEmpty(selected.UpdatedByName)
            ? Loc.GetString("generic-not-available-shorthand")
            : selected.UpdatedByName;
        StatusSelector.SelectId((int) selected.Status);
        ApplyButton.Disabled = !update.CanEdit;
        ReasonEdit.Editable = update.CanEdit;

        HistoryList.Clear();
        foreach (var entry in update.History)
        {
            var reason = entry.Reason ?? Loc.GetString("generic-not-available-shorthand");
            HistoryList.AddItem(Loc.GetString(
                "nc-police-records-history-line",
                ("time", entry.CreatedAt.ToLocalTime().ToString("g")),
                ("actor", entry.ActorName),
                ("oldStatus", StatusName(entry.PreviousStatus)),
                ("newStatus", StatusName(entry.NewStatus)),
                ("reason", reason)));
        }

        NoHistoryLabel.Visible = update.History.Count == 0;
    }

    private void SubmitSearch()
    {
        var query = SearchEdit.Text.Trim();
        OnSearch?.Invoke(query);
    }

    private void AddResultGroup(string heading, IEnumerable<NCPoliceRecordSummary> results)
    {
        var entries = results.ToList();
        if (entries.Count == 0)
            return;

        ResultsList.AddItem(heading, selectable: false);
        foreach (var result in entries)
        {
            ResultsList.AddItem(
                $"{result.CharacterName} — {StatusName(result.Status)}",
                metadata: result.CharacterId);
        }
    }

    private string GetJobName(string? jobPrototypeId)
    {
        if (jobPrototypeId != null && _prototypes.TryIndex<JobPrototype>(jobPrototypeId, out var job))
            return job.LocalizedName;

        return Loc.GetString("job-name-passenger");
    }

    private static string StatusName(NCPoliceOperationalStatus status)
    {
        return Loc.GetString($"nc-police-status-{status.ToString().ToLowerInvariant()}");
    }
}
