# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: job
  id: TraumaTeamCoroner
  name: job-name-medical-coroner
  description: job-description-medical-coroner
  playTimeTracker: NCJobMedicalCoroner
  supervisors: nc-job-supervisors-medical-command
  weight: 90
  setPreference: false
  startingGear: NCMedicalCoronerGear
  icon: JobIconMedicalDoctor
  accessGroups: [ MedicalBasic ]
  access: [ Medical_Morgue ]

- type: startingGear
  id: NCMedicalCoronerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorBlack
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesForensic
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
  storage:
    back:
    - ForensicPad
    - ForensicScanner
