# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: job
  id: TraumaTeamIntern
  name: job-name-medical-intern
  description: job-description-medical-intern
  playTimeTracker: NCJobMedicalIntern
  supervisors: nc-job-supervisors-medical-command
  weight: 20
  setPreference: false
  startingGear: NCMedicalInternGear
  icon: JobIconMedicalIntern
  accessGroups: [ MedicalBasic ]

- type: startingGear
  id: NCMedicalInternGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesLatex
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
    pocket2: BookMedicalReferenceBook
