# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: job
  id: NCMedicalTechnician
  name: job-name-medical-technician
  description: job-description-medical-technician
  playTimeTracker: NCJobMedicalTechnician
  supervisors: nc-job-supervisors-medical-command
  weight: 40
  salary: 250
  setPreference: false
  startingGear: NCMedicalTechnicianGear
  icon: JobIconMedicalDoctor
  accessGroups: [ MedicalBasic ]

- type: startingGear
  id: NCMedicalTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesBootsWork
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesColorYellow
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltUtilityEngineering
    outerClothing: ClothingOuterCoatLab
