# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: job
  id: NCPDSergeant
  name: job-name-ncpd-sergeant
  description: job-description-ncpd-sergeant
  playTimeTracker: NCJobNCPDSergeant
  supervisors: nc-job-supervisors-ncpd-command
  weight: 45
  setPreference: false
  startingGear: NCPDSergeantGear
  icon: JobIconSecurityOfficer
  accessGroups: [ NCPDBasic ]

- type: startingGear
  id: NCPDSergeantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecGrey
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatBeretSecurity
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterArmorBasic
