// SPDX-FileCopyrightText: 2026 Astro
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Personnel.UI;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._NC.Personnel;

[GenerateTypedNameReferences]
public sealed partial class NCPersonnelConsoleWindow : FancyWindow
{
    private readonly IPrototypeManager _prototypes;
    private readonly Dictionary<int, string> _positionIds = new();
    private int? _selectedCharacterId;
    private bool _selectedIsEmployee;
    private string? _selectedEmployeeJobId;
    private bool _canManage;

    public event Action<string>? OnSearch;
    public event Action<int>? OnSelectCharacter;
    public event Action<int, string, string>? OnHire;
    public event Action<int, string>? OnTerminate;
    public event Action<int, string, string>? OnChangePosition;

    public NCPersonnelConsoleWindow(IPrototypeManager prototypes)
    {
        RobustXamlLoader.Load(this);
        _prototypes = prototypes;

        PositionSelector.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            UpdateButtons();
        };
        SearchButton.OnPressed += _ => SubmitSearch();
        SearchEdit.OnTextEntered += _ => SubmitSearch();
        EmployeeList.OnItemSelected += args => SelectFromList(EmployeeList, args.ItemIndex, true);
        CandidateList.OnItemSelected += args => SelectFromList(CandidateList, args.ItemIndex, false);
        HireButton.OnPressed += _ =>
        {
            var reason = Rope.Collapse(ReasonEdit.TextRope).Trim();
            if (_selectedCharacterId is { } characterId && !_selectedIsEmployee &&
                _positionIds.TryGetValue(PositionSelector.SelectedId, out var jobId))
                OnHire?.Invoke(characterId, jobId, reason);
        };
        TerminateButton.OnPressed += _ =>
        {
            var reason = Rope.Collapse(ReasonEdit.TextRope).Trim();
            if (_selectedCharacterId is { } characterId && _selectedIsEmployee)
                OnTerminate?.Invoke(characterId, reason);
        };
        ChangePositionButton.OnPressed += _ =>
        {
            var reason = Rope.Collapse(ReasonEdit.TextRope).Trim();
            if (_selectedCharacterId is { } characterId && _selectedIsEmployee &&
                _positionIds.TryGetValue(PositionSelector.SelectedId, out var jobId) && jobId != _selectedEmployeeJobId)
                OnChangePosition?.Invoke(characterId, jobId, reason);
        };
    }

    public void UpdateState(NCPersonnelConsoleUpdateMessage state)
    {
        _canManage = state.CanManage;
        ReadOnlyLabel.Visible = !state.CanManage;
        SearchEdit.Editable = state.CanManage;
        SearchButton.Disabled = !state.CanManage;

        DepartmentLabel.Text = _prototypes.TryIndex<DepartmentPrototype>(state.DepartmentId, out var department)
            ? Loc.GetString("nc-personnel-department-line", ("department", Loc.GetString(department.Name)))
            : state.DepartmentId;

        EmployeeList.Clear();
        foreach (var employee in state.Employees)
            EmployeeList.AddItem(Loc.GetString("nc-personnel-employee-line", ("name", employee.CharacterName),
                ("job", JobName(employee.JobId))), metadata: employee.CharacterId);

        CandidateList.Clear();
        foreach (var candidate in state.Candidates)
            CandidateList.AddItem(candidate.CharacterName, metadata: candidate.CharacterId);

        _selectedCharacterId = state.SelectedCharacterId;
        var selectedEmployee = state.Employees.Find(value => value.CharacterId == state.SelectedCharacterId);
        var selectedCandidate = state.Candidates.Find(value => value.CharacterId == state.SelectedCharacterId);
        _selectedIsEmployee = selectedEmployee != null;
        _selectedEmployeeJobId = selectedEmployee?.JobId;
        SelectedLabel.Text = selectedEmployee?.CharacterName ?? selectedCandidate?.CharacterName ??
            Loc.GetString("nc-personnel-select-character");

        _positionIds.Clear();
        PositionList.Clear();
        PositionSelector.Clear();
        var selectorId = 0;
        foreach (var position in state.Positions)
        {
            var text = Loc.GetString("nc-personnel-position-line", ("job", JobName(position.JobId)),
                ("occupied", position.Occupied), ("limit", position.Limit));
            PositionList.AddItem(text, selectable: false);
            if (position.CanAssign && position.Occupied < position.Limit &&
                position.JobId != _selectedEmployeeJobId)
            {
                _positionIds[selectorId] = position.JobId;
                PositionSelector.AddItem(text, selectorId++);
            }
        }
        if (_positionIds.Count > 0)
            PositionSelector.SelectId(0);

        HistoryList.Clear();
        foreach (var entry in state.History)
        {
            HistoryList.AddItem(Loc.GetString("nc-personnel-history-line",
                ("time", entry.CreatedAt.ToLocalTime().ToString("g")),
                ("actor", entry.ActorName),
                ("action", ActionName(entry.Action)),
                ("oldJob", JobName(entry.PreviousJobId)),
                ("newJob", JobName(entry.NewJobId)),
                ("reason", HistoryReason(entry))));
        }
        NoHistoryLabel.Visible = state.History.Count == 0;
        UpdateButtons();
    }

    private void SelectFromList(ItemList list, int index, bool employee)
    {
        if (list[index].Metadata is not int characterId)
            return;
        _selectedCharacterId = characterId;
        _selectedIsEmployee = employee;
        OnSelectCharacter?.Invoke(characterId);
        UpdateButtons();
    }

    private void UpdateButtons()
    {
        HireButton.Disabled = !_canManage || _selectedCharacterId == null || _selectedIsEmployee || _positionIds.Count == 0;
        var hasDifferentPosition = _positionIds.TryGetValue(PositionSelector.SelectedId, out var selectedJob) &&
                                   selectedJob != _selectedEmployeeJobId;
        ChangePositionButton.Disabled = !_canManage || _selectedCharacterId == null || !_selectedIsEmployee ||
                                        !hasDifferentPosition;
        TerminateButton.Disabled = !_canManage || _selectedCharacterId == null || !_selectedIsEmployee;
        PositionSelector.Disabled = !_canManage || _selectedCharacterId == null || _positionIds.Count == 0;
        ReasonEdit.Editable = _canManage && _selectedCharacterId != null;
    }

    private void SubmitSearch() => OnSearch?.Invoke(SearchEdit.Text.Trim());

    private string JobName(string? jobId)
    {
        return jobId != null && _prototypes.TryIndex<JobPrototype>(jobId, out var job)
            ? job.LocalizedName
            : Loc.GetString("job-name-passenger");
    }

    private static string ActionName(string action) =>
        Loc.GetString($"nc-personnel-action-{action.ToLowerInvariant()}");

    private static string HistoryReason(NCPersonnelHistorySummary entry)
    {
        return entry.Action switch
        {
            "EntrySelected" => Loc.GetString("nc-personnel-reason-entry-selected"),
            "AdministrativeChange" => Loc.GetString("nc-personnel-reason-administrative-change"),
            "Resigned" => Loc.GetString("nc-personnel-reason-voluntary-resignation"),
            _ => entry.Reason,
        };
    }
}
