using Content.Client.Humanoid;
using Content.Shared.Clothing;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterPickerButton : ContainerButton
{
    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    public CharacterPickerButton(
        IPrototypeManager prototypeManager,
        ISharedPlayerManager playerMan,
        ButtonGroup group,
        HumanoidCharacterProfile profile,
        ProtoId<JobPrototype>? ncEmployment,
        bool isSelected)
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;
        var description = profile.Name;

        View.LoadPreview(profile);

        // NC start - Show the concrete server-owned position, never a stale department preference.
        if (ncEmployment is { } employmentId && prototypeManager.TryIndex(employmentId, out var ncJob))
        {
            description = TryGetNCDisplayDepartment(prototypeManager, employmentId, out var department)
                ? $"{description}\n{Loc.GetString(department.Name)} - {ncJob.LocalizedName}"
                : $"{description}\n{ncJob.LocalizedName}";
        }
        else
        {
            description = $"{description}\n{Loc.GetString("job-name-passenger")}";
        }
        // NC end

        Pressed = isSelected;
        DeleteButton.Visible = !isSelected;

        DescriptionLabel.Text = description;

        ConfirmDeleteButton.OnPressed += _ =>
        {
            Parent?.RemoveChild(this);
            Parent?.RemoveChild(ConfirmDeleteButton);
            OnDeletePressed?.Invoke();
        };

        DeleteButton.OnPressed += _ =>
        {
            DeleteButton.Visible = false;
            ConfirmDeleteButton.Visible = true;
        };

    }
}
