// SPDX-FileCopyrightText: 2026 Astro
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Mapping.UI;

[GenerateTypedNameReferences]
public sealed partial class NCMappingHubWindow : DefaultWindow
{
    public NCMappingHubWindow()
    {
        RobustXamlLoader.Load(this);
        Tabs.SetTabTitle(0, Loc.GetString("nc-mapping-hub-tab-tools"));
        Tabs.SetTabTitle(1, Loc.GetString("nc-mapping-hub-tab-floors"));
        Tabs.SetTabTitle(2, Loc.GetString("nc-mapping-hub-tab-zones"));
    }
}
