# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: job
  id: MilitechOperative
  name: job-name-militech-operative
  description: job-description-militech-operative
  playTimeTracker: NCJobMilitechOperative
  supervisors: nc-job-supervisors-militech-command
  weight: 70
  setPreference: false
  startingGear: MilitechOperativeGear
  icon: JobIconSecurityOfficer
  accessGroups: [ MilitechBasic ]
  access: [ Militech_Operative, Militech_Armory ]

- type: startingGear
  id: MilitechOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecGrey
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterArmorBasic
