# SPDX-FileCopyrightText: 2026 Astro
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Community Funding Additional Permission applies; see COMMUNITY-FUNDING-PERMISSION.md.

- type: job
  id: BiotechnicaTech
  name: job-name-biotechnica-tech
  description: job-description-biotechnica-tech
  playTimeTracker: NCJobBiotechnicaTech
  supervisors: nc-job-supervisors-biotechnica-management
  weight: 50
  setPreference: false
  startingGear: BiotechnicaTechGear
  icon: JobIconStationEngineer
  accessGroups: [ BiotechBasic ]
  access: [ Biotech_Tech ]

- type: startingGear
  id: BiotechnicaTechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineering
    shoes: ClothingShoesBootsWork
    head: ClothingHeadHatHardhatYellow
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesColorYellow
    id: EngineerPDA
    ears: ClothingHeadsetEngineering
    belt: ClothingBeltUtilityEngineering
